import {StyleSheet} from'react-native';

export const globalStyles = StyleSheet.create({
    invmain: {
      flexDirection: "row",
      paddingTop: 20,
      height: "100%",
    },
    invfilters: {
      width: "24%",
      paddingLeft: 25,
      paddingVertical: 40,
    },
    invtable: {
      width: "75%",
    },
    invcontainer: {
      flex: 1,
      width: 1200,
      overflow: "scroll",
      paddingHorizontal: 20,
    },
    searchInput: {
      height: 40,
      borderWidth: 1,
      borderColor: "#ccc",
      borderRadius: 5,
      paddingHorizontal: 10,
      marginBottom: 20,
      color: "black",
      paddingVertical: 10,
    },
    invrow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      paddingHorizontal: 10,
      borderBottomWidth: 1,
      borderColor: "#ccc",
    },
    invheaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 15,
      paddingHorizontal: 10,
      marginBottom: 10,
      borderWidth: 1,
      borderRadius: 5,
      borderColor: "transparent",
      backgroundColor: "#E68A5C",
    },
    invheader: {
      flex: 1,
      fontSize: 14,
      color: "#fff",
      alignItems: "center",
      justifyContent: "center",
    },
    checkbox: {
      paddingRight: 12,
      marginRight: 10, 
     },
    invcell: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      fontSize: 12,
      color: "#48505E",
    },
    button: {
      backgroundColor: "#E68A5C",
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 5,
      alignItems: "center",
      marginTop: 20,
    },
    disabledButton: {
      backgroundColor: "#ccc",
    },


    container: {
        flex: 1,
        paddingHorizontal: 35,
        paddingVertical: 25,
        color: 'black',
        backgroundColor: 'white',
        padding: 20,
        width: '80%',
        maxHeight: '100%',
        minHeight: '85%',
        borderRadius: 8,
        // elevation: 5,
      },
      overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalContainer: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        elevation: 5, // For shadow (macOS)
      },
      closeButton: {
        height: 20,
        marginBottom: 10,
        borderRadius: 50,
        backgroundColor: '#fff',
        justifyContent: 'flex-end',
        flexDirection: 'row',
        alignItems: 'center',
      },
      input: {
        width: '100%',
        height: 'auto',
        borderWidth: 1,
        borderColor: '#667085',
        color: '#48505E',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 5,
        paddingHorizontal: 10,
        marginBottom: 8,
        paddingVertical: 10,
      },
      label: {
        color: '#333333',
        marginBottom: 2,
        fontWeight: '300',
        fontSize: 12,
      },
      button: {
        height: 40,
        backgroundColor: '#E68A5C',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        marginTop: 10,
        paddingHorizontal: 20
      },
      close: {
        height: 40,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        marginTop: 10,
      },
      buttonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
      },
      closeText: {
        color:'#E68A5C',
        fontSize: 14,
        fontWeight: '500',
      },
      buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 15
      },
      container: {
        flex: 1,
        paddingHorizontal: 35,
        paddingVertical: 25,
        color: 'black',
        backgroundColor: 'white',
        padding: 20,
        width: '80%',
        maxHeight: '100%',
        minHeight: '85%',
        borderRadius: 8,
        // elevation: 5,
      },
      overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalContainer: {
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        elevation: 5, // For shadow (macOS)
      },
      closeButton: {
        height: 20,
        marginBottom: 10,
        borderRadius: 50,
        backgroundColor: '#fff',
        justifyContent: 'flex-end',
        flexDirection: 'row',
        alignItems: 'center',
      },
      input: {
        width: '85%',
        height: 'auto',
        borderWidth: 1,
        borderColor: '#667085',
        color: '#48505E',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 5,
        paddingHorizontal: 10,
        marginBottom: 8,
        paddingVertical: 10,
      },
      label: {
        color: '#333333',
        marginBottom: 2,
        fontWeight: '300',
        fontSize: 12,
      },
      text: {
        justifyContent: 'center',
        color: '#333333',
        marginBottom: 2,
        fontWeight: '300',
        fontSize: 12,
      },
      button: {
        height: 40,
        backgroundColor: '#E68A5C',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        marginTop: 10,
        paddingHorizontal: 20,
      },
      filters: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
      },
      close: {
        height: 40,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        marginTop: 10,
      },
      buttonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
      },
      closeText: {
        color: '#E68A5C',
        fontSize: 14,
        fontWeight: '500',
      },
      buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 15,
      },
      filterSection: {
        marginBottom: 10,
        width: '24%',
        marginTop: 20,
      },
      selectedFilterContainer: {
        width: '75%',
        marginLeft: 30,
        marginTop: 20,
      },
      filterContainer: {
        flexWrap: 'wrap',
        width: '100%',
        marginBottom: 10,
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#c0c0c0',
      },
      filterHeader: {
        height: 30,
        width: '100%',
        paddingHorizontal: 20,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#E68A5C',
        borderRadius: 5,
        marginBottom: 5,
      },
      filterHeaderText: {
        fontSize: 14,
        fontWeight: '500',
      },
      filterButton: {
        height: 30,
        width: '100%',
        paddingHorizontal: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: '#c0c0c0',
        borderTopWidth: 1,
      },
      first: {
        borderTopWidth: 0,
      },
      filterText: {
        color: '#999',
        fontSize: 14,
      },
      datePicker: {
        height: 'auto',
        width: '65%',
        marginLeft: 30,
      },
      picker: {
        width: '85%',
      },
      acknowledgmentContainer: {
        backgroundColor: "#E68A5C",
        padding: 10,
        alignItems: "center",
      },
      acknowledgmentText: {
        color: "white",
      },
      
  });